module.exports = {
  PROJECT_ADDED: "PROJECT_ADDED",
  SECTION_ADDED: "SECTION_ADDED",
  CARD_ADDED: "CARD_ADDED",
  ON_SECTION_POS_CHANGE: "ON_SECTION_POS_CHANGE",
  ON_CARD_POS_CHANGE: "ON_CARD_POS_CHANGE",
}
